### Situação:

Usando os dados das licitações do ano de 2021, no Rio Grande do Sul, fazer uma análise dos principais itens licitados e das áreas que receberam maior investimento por meio de licitações

Link: http://dados.tce.rs.gov.br/dataset?groups=licitacoes&q=consolidado

### Imports

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import spacy 
import nltk

/Users/ionasantana/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/feature_extraction/image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
/Users/ionasantana/opt/anaconda3/envs/nlp_course/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Depr

In [5]:
files

['memcomissao.csv',
 'evento_lic.csv',
 'documento_lic.csv',
 'licitante.csv',
 'licitacao.csv',
 'item.csv',
 'pessoas.csv',
 'dotacao_lic.csv',
 'comissao.csv',
 'membrocons.csv',
 'proposta.csv',
 'item_prop.csv',
 'lote_prop.csv',
 'lote.csv']

### Pré-processamento Dados

In [8]:
cols = ['CD_ORGAO', 'NM_ORGAO', 'NR_LICITACAO', 'CD_TIPO_MODALIDADE','DS_OBJETO', 'VL_LICITACAO', 'BL_COVID19']
licitacao_21 = licitacao[cols]

In [9]:
licitacao_21 = licitacao_21.dropna()

In [10]:
licitacao_21.head(3)

CD_ORGAO                                       NM_ORGAO  NR_LICITACAO  \
0     53100                               PM DE NOVA PALMA           1.0   
1     86800                         PM DE BOA VISTA DO SUL           2.0   
2     45003  SERVIÇO AUTÔN. MUN. DE ÁGUA E ESGOTO - CX.SUL          46.0   

  CD_TIPO_MODALIDADE                                          DS_OBJETO  \
0                TMP  CONTRATAÇÃO GLOBAL DE EMPRESA PARA CONSTRUÇÃO ...   
1                PRP  Contratação de empresa para prestação de servi...   
2                PRP  Aquisição de 80.000 (oitenta mil) quilogramas ...   

   VL_LICITACAO BL_COVID19  
0      259765.0          N  
1      390625.0          N  
2      833800.0          N

In [11]:
item_licitacao = item.iloc[:, 0:12]
item_licitacao['BL_COVID19'] = item['BL_COVID19'] 

In [12]:
item_licitacao.isna().sum()

CD_ORGAO                    0
NR_LICITACAO                0
ANO_LICITACAO               0
CD_TIPO_MODALIDADE          0
NR_LOTE                     0
NR_ITEM                     0
NR_ITEM_ORIGINAL            0
DS_ITEM                     1
QT_ITENS                    0
SG_UNIDADE_MEDIDA           0
VL_UNITARIO_ESTIMADO    39446
VL_TOTAL_ESTIMADO       39446
BL_COVID19                  0
dtype: int64

In [13]:
item_licitacao = item_licitacao.dropna()

In [14]:
len(licitacao_21), len(item_licitacao)

(87469, 932800)

In [15]:
licitacao_21['covid'] = np.where((licitacao_21['BL_COVID19'] == 'S'), ' covid19', '')
licitacao_21['DS_OBJETO'] = licitacao_21['DS_OBJETO'] + licitacao_21['covid']

In [16]:
licitacao_21 = licitacao_21.drop(['BL_COVID19', 'covid'], axis = 1)

In [18]:
item_licitacao['covid'] = np.where((item_licitacao['BL_COVID19'] == 'S'), ' covid19', '')
item_licitacao['DS_ITEM'] = item_licitacao['DS_ITEM'] + item_licitacao['covid']

In [19]:
item_licitacao = item_licitacao.drop(['BL_COVID19', 'covid'], axis = 1)

In [20]:
item_licitacao['ANO_LICITACAO'].unique()
item_licitacao.drop(['ANO_LICITACAO'], axis = 1).head(3)

CD_ORGAO  NR_LICITACAO CD_TIPO_MODALIDADE  NR_LOTE  NR_ITEM  \
0     44500         274.0                CPC        1        1   
1     56900          25.0                TMP        1        1   
2     56900          25.0                TMP        1        2   

  NR_ITEM_ORIGINAL                                            DS_ITEM  \
0                1  Credenciamento de academias de ginástica e mus...   
1             1.1   PLACA DE OBRA (PARA CONSTRUCAO CIVIL) EM CHAPA...   
2             1.2        TAPUME COM COMPENSADO DE MADEIRA. AF_05/2018   

  QT_ITENS SG_UNIDADE_MEDIDA  VL_UNITARIO_ESTIMADO  VL_TOTAL_ESTIMADO  
0        1                UN                 50.00              50.00  
1        6                M2                272.49            1634.94  
2       71                M2                128.69            9136.99

### Pré-processamento Texto

In [33]:
# Libs adicionais de NLP
import spacy 
# import pt_core_news_lg
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import re

In [39]:
nlp=spacy.load("pt_core_news_sm")
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/ionasantana/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
stopwords = nltk.corpus.stopwords.words('portuguese')

filter_out = stopwords + ['kg', 'm', 'cm', 'mm', 'mg', 'ml', 'm²', '-', '+', '=', 'mcg', 'nº', 'g', 'ª', 'º']

<table ><tr><th>Character</th><th>Description</th><th>Example Pattern Code</th><th >Exammple Match</th></tr>

<tr ><td><span >\d</span></td><td>A digit</td><td>file_\d\d</td><td>file_25</td></tr>

<tr ><td><span >\w</span></td><td>Alphanumeric</td><td>\w-\w\w\w</td><td>A-b_1</td></tr>



<tr ><td><span >\s</span></td><td>White space</td><td>a\sb\sc</td><td>a b c</td></tr>



<tr ><td><span >\D</span></td><td>A non digit</td><td>\D\D\D</td><td>ABC</td></tr>

<tr ><td><span >\W</span></td><td>Non-alphanumeric</td><td>\W\W\W\W\W</td><td>*-+=)</td></tr>

<tr ><td><span >\S</span></td><td>Non-whitespace</td><td>\S\S\S\S</td><td>Yoyo</td></tr></table>

<table ><tr><th>Character</th><th>Description</th><th>Example Pattern Code</th><th >Exammple Match</th></tr>

<tr ><td><span >+</span></td><td>Occurs one or more times</td><td>	Version \w-\w+</td><td>Version A-b1_1</td></tr>

<tr ><td><span >{3}</span></td><td>Occurs exactly 3 times</td><td>\D{3}</td><td>abc</td></tr>



<tr ><td><span >{2,4}</span></td><td>Occurs 2 to 4 times</td><td>\d{2,4}</td><td>123</td></tr>



<tr ><td><span >{3,}</span></td><td>Occurs 3 or more</td><td>\w{3,}</td><td>anycharacters</td></tr>

<tr ><td><span >\*</span></td><td>Occurs zero or more times</td><td>A\*B\*C*</td><td>AAACC</td></tr>

<tr ><td><span >?</span></td><td>Once or none</td><td>plurals?</td><td>plural</td></tr></table>

In [72]:
def pre_processing(sentence):
    sentence = sentence.lower()
    sentence = re.sub(r"[^\w\s]", "", sentence)
    sentence = re.sub(r"[0-9]+", "", sentence)
    sentence = re.sub(r"/+", "", sentence)
    sentence = re.sub(r" {2,}", " ", sentence)

    #Tokenização
    doc = nlp(sentence)

    tokens=[token.text for token in doc]
    tokens=[token for token in tokens if token not in filter_out]

    return tokens


In [75]:
print(pre_processing('testando 1 2 3 aa'))

['testando', 'aa']


In [76]:
item_licitacao['DS_ITEM_TOKEN'] = item_licitacao['DS_ITEM'].apply(lambda sentece: pre_processing(sentece))


In [77]:
item_licitacao.to_csv('item_licitacao_token.csv')

In [78]:
licitacao_21['DS_OBJETO_TOKEN'] = licitacao_21['DS_OBJETO'].apply(lambda sentece: pre_processing(sentece))


In [79]:
licitacao_21.to_csv('licitacao_21_token.csv')

### Construção dos modelos

In [80]:
licitacao_21.head(3) #retirar os (), depois?

CD_ORGAO                                       NM_ORGAO  NR_LICITACAO  \
0     53100                               PM DE NOVA PALMA           1.0   
1     86800                         PM DE BOA VISTA DO SUL           2.0   
2     45003  SERVIÇO AUTÔN. MUN. DE ÁGUA E ESGOTO - CX.SUL          46.0   

  CD_TIPO_MODALIDADE                                          DS_OBJETO  \
0                TMP  CONTRATAÇÃO GLOBAL DE EMPRESA PARA CONSTRUÇÃO ...   
1                PRP  Contratação de empresa para prestação de servi...   
2                PRP  Aquisição de 80.000 (oitenta mil) quilogramas ...   

   VL_LICITACAO                                    DS_OBJETO_TOKEN  
0      259765.0  [contratação, global, empresa, construção, par...  
1      390625.0  [contratação, empresa, prestação, serviços, tr...  
2      833800.0  [aquisição, oitenta, mil, quilogramas, ortopol...

In [81]:
item_licitacao.head(3)

CD_ORGAO  NR_LICITACAO  ANO_LICITACAO CD_TIPO_MODALIDADE  NR_LOTE  NR_ITEM  \
0     44500         274.0           2021                CPC        1        1   
1     56900          25.0           2021                TMP        1        1   
2     56900          25.0           2021                TMP        1        2   

  NR_ITEM_ORIGINAL                                            DS_ITEM  \
0                1  Credenciamento de academias de ginástica e mus...   
1             1.1   PLACA DE OBRA (PARA CONSTRUCAO CIVIL) EM CHAPA...   
2             1.2        TAPUME COM COMPENSADO DE MADEIRA. AF_05/2018   

  QT_ITENS SG_UNIDADE_MEDIDA  VL_UNITARIO_ESTIMADO  VL_TOTAL_ESTIMADO  \
0        1                UN                 50.00              50.00   
1        6                M2                272.49            1634.94   
2       71                M2                128.69            9136.99   

                                       DS_ITEM_TOKEN  
0  [credenciamento, academias, ginástica, muscula...  
1  [placa, obra, construcao, civil, chapa, galvan...  
2               [tapume, compensado, madeira, af, _]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
import gensim
import gensim.corpora as corpora
from gensim.utils import simple_preprocess
from gensim.models import CoherenceModel
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

In [10]:
item_licitacao.columns

Index(['Unnamed: 0', 'CD_ORGAO', 'NR_LICITACAO', 'ANO_LICITACAO',
       'CD_TIPO_MODALIDADE', 'NR_LOTE', 'NR_ITEM', 'NR_ITEM_ORIGINAL',
       'DS_ITEM', 'QT_ITENS', 'SG_UNIDADE_MEDIDA', 'VL_UNITARIO_ESTIMADO',
       'VL_TOTAL_ESTIMADO', 'DS_ITEM_TOKEN'],
      dtype='object')

In [17]:
lic= [d.split() for d in item_licitacao['DS_ITEM_TOKEN']]


In [18]:
id2word = corpora.Dictionary(lic)

In [19]:
texts = item_licitacao['DS_ITEM_TOKEN']

In [21]:
corpus = [id2word.doc2bow(text.split()) for text in texts]

# Visualização
print(corpus[:1])

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 2), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 3), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1)]]


In [22]:
# Corpus num formado simplificado (term-frequency)
[[(id2word[id], freq) for id, freq in cp] for cp in corpus[:1]]

[[("'academias',", 1),
  ("'cada',", 1),
  ("'canoas',", 1),
  ("'credenciado',", 1),
  ("'desembolsado',", 1),
  ("'escolhido',", 1),
  ("'estabelecimento',", 2),
  ("'exercícios',", 1),
  ("'físicos',", 1),
  ("'ginástica',", 1),
  ("'matriculado',", 1),
  ("'ministrem',", 1),
  ("'município',", 3),
  ("'musculação',", 1),
  ("'outro',", 1),
  ("'r',", 1),
  ("'servidor',", 1),
  ("'servidor']", 1),
  ("'valor',", 1),
  ("'âmbito',", 1),
  ("['credenciamento',", 1)]]

In [37]:
from sklearn.decomposition import LatentDirichletAllocation

In [62]:
filter_out = filter_out + ['cor', 'un', 'branco', 'unidades', 
'litros', 'af', 'mgml', 'nbr', 'dn', 'eou', 'referência', 'conforme',
'demais', 'deverá', 'tipo', 'r', 'gb']


In [63]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words=filter_out)

In [64]:
dtm = cv.fit_transform(item_licitacao['DS_ITEM_TOKEN'])

In [65]:
LDA = LatentDirichletAllocation(n_components=10,random_state=42)

In [66]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=10, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=42, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [72]:
LDA.components_

array([[7.27442757e+02, 1.00000000e-01, 5.61991398e+02, ...,
        1.00000002e-01, 1.00000000e-01, 1.00000972e-01],
       [1.26559140e+02, 1.00000000e-01, 1.09427288e+02, ...,
        1.00000001e-01, 1.00000000e-01, 3.09996186e+00],
       [1.98652575e+00, 1.00000000e-01, 2.18217534e+01, ...,
        1.00535021e-01, 2.10000000e+00, 1.00007282e-01],
       ...,
       [2.20929535e+01, 1.00000000e-01, 1.00003131e-01, ...,
        1.00000001e-01, 1.00000000e-01, 1.00000000e-01],
       [1.21000501e-01, 1.00000000e-01, 1.00001602e-01, ...,
        1.50994650e+01, 1.00000000e-01, 1.00000000e-01],
       [7.13792662e-01, 1.00000000e-01, 1.00003808e-01, ...,
        1.00000001e-01, 1.00000000e-01, 1.00000000e-01]])

In [73]:
single_topic = LDA.components_[0]
# Returns the indices that would sort this array.
single_topic.argsort()

array([35215, 72015, 36439, ..., 75143, 53586, 65253])

In [76]:
top_word_indices = single_topic.argsort()[-10:]

In [77]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

firme
livre
casca
boa
grau
verde
primeira
tamanho
médio
qualidade


Após o processamento, se encontrou palavras como cor, un, af, tipo - então elas foram adicionadas no filtro e foi se processado novamente

In [78]:
for index,topic in enumerate(LDA.components_):
    print(f'Top 10 tópicos dos itens#{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-10:]])
    print('\n')

Top 10 tópicos dos itens#0
['firme', 'livre', 'casca', 'boa', 'grau', 'verde', 'primeira', 'tamanho', 'médio', 'qualidade']


Top 10 tópicos dos itens#1
['cobre', 'empresa', 'saúde', 'municipal', 'horas', 'contratação', 'exame', 'serviços', 'cabo', 'covid']


Top 10 tópicos dos itens#2
['conector', 'seringa', 'ampola', 'injetável', 'sistema', 'frasco', 'solução', 'tubo', 'ar', 'concreto']


Top 10 tópicos dos itens#3
['contendo', 'mínimo', 'mínima', 'fabricação', 'entrega', 'meses', 'produto', 'data', 'validade', 'embalagem']


Top 10 tópicos dos itens#4
['lâmpada', 'ser', 'tamanho', 'cloridrato', 'ca', 'largura', 'parafuso', 'tecido', 'comprimido', 'aço']


Top 10 tópicos dos itens#5
['impressora', 'lubrificante', 'linha', 'lixo', 'oleo', 'ar', 'saco', 'fita', 'óleo', 'filtro']


Top 10 tópicos dos itens#6
['modelo', 'usb', 'kit', 'capacidade', 'mínima', 'motor', 'placa', 'veículo', 'ano', 'mínimo']


Top 10 tópicos dos itens#7
['lonas', 'base', 'largura', 'mínimo', 'pintura', 'altura

In [79]:
dtm

<932800x84245 sparse matrix of type '<class 'numpy.longlong'>'
	with 7514684 stored elements in Compressed Sparse Row format>

In [80]:
dtm.shape

(932800, 84245)

In [81]:
topic_results = LDA.transform(dtm)

In [82]:
topic_results.shape

(932800, 10)

In [83]:
topic_results[0].round(2)

array([0.  , 0.75, 0.  , 0.  , 0.09, 0.  , 0.13, 0.  , 0.  , 0.  ])

In [84]:
item_licitacao['DS_ITEM_TOKEN'].head()

0    ['credenciamento', 'academias', 'ginástica', '...
1    ['placa', 'obra', 'construcao', 'civil', 'chap...
2       ['tapume', 'compensado', 'madeira', 'af', '_']
3    ['poda', 'altura', 'árvore', 'diâmetro', 'tron...
4    ['locacao', 'container', 'x', 'alt', 'escritor...
Name: DS_ITEM_TOKEN, dtype: object

In [85]:
topic_results.argmax(axis=1)

array([1, 8, 7, ..., 1, 6, 6])

In [86]:
item_licitacao['Topic'] = topic_results.argmax(axis=1)

In [89]:
item_licitacao[ ['DS_ITEM', 'Topic']].head()

DS_ITEM  Topic
0  Credenciamento de academias de ginástica e mus...      1
1  PLACA DE OBRA (PARA CONSTRUCAO CIVIL) EM CHAPA...      8
2       TAPUME COM COMPENSADO DE MADEIRA. AF_05/2018      7
3  PODA EM ALTURA DE ÁRVORE COM DIÂMETRO DE TRONC...      4
4  LOCACAO DE CONTAINER 2,30  X  6,00 M, ALT. 2,5...      7

### Análise dos dados

### Conclusão

Quais foram as áreas com maiores investimentos?

E quais foram os principais itens licitados nelas?